services:
  traefik-generator:
    build: generator
    env_file: .env
    restart: 'no'
    volumes:
      - ./config:/usr/src/traefik
      - ${SERVICES_CONFIG_FILE}:/usr/src/app/services.js
      - ${SERVICES_EXPORTED_FILE}:/usr/src/app/monitor/exported.js