version: '3.9'

services:
  traefik-generator:
    build: generator
    env_file: .env
    restart: 'no'
    volumes:
      - ./config:/usr/src/traefik
      - ${EXPORT_SERVICES_DIR}:/usr/src/app/monitor
      - ${PWD}/services.js:/usr/src/app/services.js