services:
  auth:
    hostname: traefikAuth
    container_name: traefik-auth
    build:
      dockerfile: forwardAuth/Dockerfile
    volumes:
      - ./forwardAuth:/usr/src/app
      - ${SERVICES_CONFIG_FILE}:/usr/src/services.js
      - /usr/src/app/node_modules
    env_file: .env
    networks:
      - ${NETWORK_NAME}

  db:
    hostname: traefikDB
    container_name: traefik-db
    image: mongo
    restart: always
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - dbData:/data/db
    networks:
      - ${NETWORK_NAME}

  traefik:
    image: traefik
    container_name: traefik-proxy
    restart: unless-stopped
    env_file: .env
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/etc/traefik
      - ./logs:/var/logs
    networks:
      - ${NETWORK_NAME}

volumes:
  dbData:

networks:
 ${NETWORK_NAME}:
    external: true
